# Generated by Django 4.2.1 on 2024-05-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraccount_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(default='image/male user.png', upload_to='user_images/'),
        ),
    ]
