# Generated by Django 4.2.1 on 2024-05-28 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_useraccount_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_deleted',
        ),
    ]
