# Generated by Django 4.2.1 on 2024-05-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_useraccount_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(default='media\\male user.png', upload_to='user_images/'),
        ),
    ]
