# Generated by Django 4.2.1 on 2024-05-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_chapter_unit_question_chapter_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField()),
                ('user_prompt', models.TextField()),
                ('output_format', models.JSONField()),
                ('default_category', models.CharField(blank=True, max_length=100)),
                ('output_value_only', models.BooleanField(default=False)),
                ('model', models.CharField(default='gpt-3.5-turbo', max_length=100)),
                ('temperature', models.FloatField(default=1)),
                ('num_tries', models.IntegerField(default=3)),
                ('verbose', models.BooleanField(default=False)),
            ],
        ),
    ]
