# Generated by Django 4.2.1 on 2024-05-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_chatinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='videoId',
            field=models.CharField(blank=True, max_length=300000, null=True),
        ),
    ]
