# Generated by Django 4.2.1 on 2024-05-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_chapter_videoid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatInteraction',
        ),
    ]
