# Generated by Django 4.2.1 on 2024-06-01 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatpdf', '0002_pdfdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatpdf.pdfdocument'),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
