# Generated by Django 4.2.1 on 2024-06-01 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatpdf', '0003_alter_messages_chat_alter_pdfdocument_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Chats',
        ),
    ]
