# Generated by Django 4.2.1 on 2024-06-01 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatpdf', '0005_chats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chats',
        ),
    ]
