# Generated by Django 4.2.1 on 2024-06-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatpdf', '0007_alter_pdfdocument_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='pdf_name',
            field=models.CharField(default='pdf', max_length=255),
        ),
    ]
